npm i mysql
npm i qrcode-terminal
npm i whatsapp-web.js
npm i mysql
npm i alexa-bot-api-v4
npm i g-i-s
npm i genius-lyrics
npm i youtube-search-without-api-key
npm i get-json
npm i translate-google
npm install openai
npm i lolcatjs
